name: "Required Labels Action"
description: "This action prints the comment on an issue if the required labels are not added in the issue. The required actions can be added in the action input using comma seperated values"
branding:
  icon: "alert-octagon"
  color: "green"
inputs:
  labels: # id of input
    description: "Required labels"
    required: true
  GITHUB_TOKEN:
    description: "Github Token"
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
