name: "Required Labels Action"
description: "Notifies on issue if required labels are not added"
inputs:
  labels: # id of input
    description: "Required labels"
    required: true
  GITHUB_TOKEN:
    description: "Github Token"
    required: true

runs:
  using: "node12"
  main: "dist/index.js"
