on:
  issues:
    types: [opened]

jobs:
  required_labels:
    runs-on: ubuntu-latest
    name: Required Labels
    steps:
      - name: Required Labels
        uses: muhaddimu/required-labels@master
        with:
          labels: "Bug"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
